### ISSUE TITLE
App Dies If No Internet Connection

### ISSUE THREAD

**Issue by say25** [cuappdev/big-red-shuttle#43]
Steps to reproduce.
1. Turn off internet connection.
2. Launch App

Potential Solution:
Use last downloaded version of schedule globally if no internet connection on applicationDidX in AppDelegate?

**Comment by say25** [comment]
As per #46, it was thought it would be better to locally store JSON information and update local file when able to connect to internet.

**Comment by anniexcheng** [comment]
Merge in e910886
