### ISSUE TITLE
No Current Location Button on Navigation Screen

### ISSUE THREAD

**Issue by say25** [cuappdev/big-red-shuttle#44]
Not sure if this is by design or not. Seems like a current location button would be more important than an About button on this screen.

**Comment by anniexcheng** [comment]
Hmm not sure if that's necessary because when you click on a stop, you can get directions to the stop. We do show your current location as a blue dot.

**Comment by say25** [comment]
Maybe that makes sense then but its kinda strange as it is still "default/standard" for most maps to have the current location button. I agree on the scale we are talking about you will probably be in the field of view anyway but it might just be what users expect. Not sure why it makes sense to put about on that screen at all though. maybe an about tab is more appropriate or it would fit better under emergency

**Comment by anniexcheng** [comment]
I think that design decision was made because users interact most with the navigation view, and having the about button there will result in better marketing for us + BRS haha

**Comment by say25** [comment]
Guess it makes sense. Probably will be a worthy future improvement if users find its confusing or a desired feature. Closing for now.
